# Generated by Django 5.2.12 on 2026-03-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodtruckapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email_list",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="email_list",
            name="number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="email_list",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
